
trigger:
- main

variables:
- name: 2022MSBuildPath
  value: C:\Program Files\Microsoft Visual Studio\2022\Professional\Msbuild\Current\Bin\MSBuild.exe
- name: GitToolLocation
  value: C:\Program Files\Git\bin\git.exe
- name: BranchName
  value: development
- name: GitHubPath
  value: D:\Git\Test

pool: Default


steps:
- script: |
    rmdir /S /Q D:\Git\Test
  displayName: 'Delete directory'

- script: |
    mkdir D:\Git\Test
  displayName: CreateDirectory

#- script: |
#    cd /d $(GitHubPath)
#    "$(GitToolLocation)" 
#  displayName: GitClone 

- script: |
    cd /d $(GitHubPath)
    "$(GitToolLocation)" clone https://github.com/Mohammed-Abubakkar-Siddiq/maui-toolkit-pipeline.git -b $(BranchName)
  displayName: GitClone  

- script: |
    "$(2022MSBuildPath)" "$(GitHubPath)\maui-toolkit-pipeline\src\DummyProjectTest.sln" /t:Restore
  displayName: ProjectRestore

- script: |
    "$(2022MSBuildPath)" "$(GitHubPath)\maui-toolkit-pipeline\src\DummyProjectTest.sln" /p:Configuration=Release
  displayName: Compilation

- task: NuGetCommand@2
  inputs:
    command: pack
    versioningScheme: byPrereleaseNumber
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'
    packagesToPack: '$(GitHubPath)\maui-toolkit-pipeline\src\DummyProjectTest\DummyProjectTest.csproj'
    packDestination: '$(GitHubPath)'