
trigger:
- main

variables:
- name: 2022MSBuildPath
  value: C:\Program Files\Microsoft Visual Studio\2022\Professional\Msbuild\Current\Bin\MSBuild.exe
- name: GitToolLocation
  value: C:\Program Files\Git\bin\git.exe
- name: BranchName
  value: development
- name: GitHubPath
  value: D:\Git\Dev

pool: Default


steps:
- script: |
    cd /d $(GitHubPath)
    "$(GitToolLocation)" clone https://SyncfusionBuild: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@github.com/essential-studio/maui-kanban -b $(BranchName)
  displayName: GitClone



