
trigger:
- main

variables:
  2022MSBuildPath: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Msbuild\Current\Bin\MSBuild.exe'
  GitToolLocation: 'C:\Program Files\Git\bin\git.exe'
  BranchName: 'development'

pool: Default


steps:
- script: |
    "GitToolLocation" 



